- renovate.json
This prevents version pinning for the `@financial-times/n-ui` package.
The package has its own release process that depends on a ranged version.
On a major release, Renovate should still open a pull requests for us.
> Add support for n-ui

- renovate.json
We should ignore Origami components included as dependencies.
These packages need to match the same version as in bower.json.
Save the pending change in the Renovate master issue so we're at least aware there's a new version out.
Closes https://github.com/Financial-Times/next/issues/214.
> Origami support

- renovate.json
Include a number of FT specific package naming conventions.
While `^@financial-times` will cover most, this just extends our reach a little more.
> Extend package pinning

- renovate.json
The default prefix is `renovate/`.
We should avoid slashes in the branch name, as a limitation of git means we then shouldn't use `renovate` as a branch name.
See https://github.com/renovatebot/config-help/issues/108#issuecomment-430576178 for more information.
> Set a branch prefix

- renovate.json
We're going to trust Renovate to do the right thing i.e. `pin` these dependencies for apps and `widen` or `replace` them for libraries.
See: https://renovatebot.com/docs/configuration-options/#rangestrategy
> Change `rangeStrategy` to 'auto' for FT packages

- renovate.json
From 2 an hour to 4.
We are hitting the rate limit quickly when onboarding Renovate with new projects.
> Increase the hourly PR rate limit

- renovate.json
See https://renovatebot.com/docs/configuration-options/#ignoredeps for more information on ignoring dependencies.
We are ignoring bower to prevent Renovate from creating deprecation warning issues for every repository that depends on @financial-times/n-ui.
> Ignore the bower package

- renovate.json
Because of issues in Node 8.14, we do not want to raise pull requests for upgrading the version of node in our projects.
We will deal with upgrades as part of a transformation across all repositories.
This is only until we are happy that our systems are stable on the latest versions of node again.
Resolves https://github.com/Financial-Times/next/issues/280.
Relates to the header limit issues we are currently seeing, https://github.com/Financial-Times/next-bugs/issues/222.
> Ignore upgrades to node

- renovate.json
Assumes that all x-dash packages are prefixed with a package name of `@financial-times/x-`.
See https://renovatebot.com/docs/noise-reduction/#package-grouping for more information.
Resolves #19.
> Group x-dash packages as a mono-repository

- renovate.json
This will get Renovate to open pull requests for major version of @financial-times/n-gage and @financial-times/n-heroku-tools, grouping the changes into a single pull request.
For the current major version, n-gage v3 and n-heroku-tools v8, we should add a comment to the pull requests Renovate opens on app repositories explaining that the app will need to be migrated to the new way of deploying to Heroku.
See https://github.com/Financial-Times/next/wiki/Heroku-review-apps-deployment for more information.
I've opened https://github.com/orgs/Financial-Times/projects/40 as a project board to add the pull requests to.
> Group n-heroku-tools and n-gage as "next build tools"

- README.md
- renovate.json
We would like Renovate to open pull requests on our repositories when there are new versions of node available.
There are several files in our repository that will need changing...
* `.nvmrc`
* `.circleci/config.yml`
* `package.json`
We have already pinned the version of node used in all of our apps. With Renovate opening pull requests to upgrade node, we can release upgrades in isolation to code changes.
Resolves #26.
> Enable Renovate to manage node versions

- renovate.json
We have a handful of packages published to npm and Bower. They need treating like Origami components.
In projects that depend on these packages, we should also not pin to a specific version so that the versions between Bower and npm are the same.
> chore: ignore packages publised to bower

- README.md
- renovate.json
Updating the renovate.json and the package readme to replace references to the anvil monorepo which has now been renamed Page Kit https://github.com/Financial-Times/dotcom-page-kit.
> Update references to the page kit monorepo (formerly anvil)

- renovate.json
This may help with upgrading the dev dependencies of the Page Kit project.
While this is potentially unnecessary, it is more explicit about what we want Renovate to do with these packages.
> feat: update configuration for Page Kit packages

- renovate.json
> :wave::skin-tone-2: Hi folks, there’s a small billion (slight emphasis) of renovate n-express builds queued on CircleCI, slowing other builds/PRs getting through. Is there a way these could be applied outside core work hours in future? Thank you :pray::skin-tone-2:
Adds the [`schedule:nonOfficeHours
` preset](https://docs.renovatebot.com/presets-schedule/#schedulenonofficehours) which sets the following:
```json
{
"schedule": [
"after 10pm every weekday",
"before 5am every weekday",
"every weekend"
]
}
```
This will mean dependency updates are only raised out of hours, any important updates in core hours can be forced by [updating the master issue](https://renovate.whitesourcesoftware.com/blog/introducing-renovates-master-issue/).
Also remove the configuration for `n-ui` which should …
> Move renovate activity outside of London working hours to reduce strain on Continuous Integration

- renovate.json
We are seeing lots of activity from existing branches within work hours, this should mean that updates only happen outside of work hours.
Figured this out by going through the process at https://github.com/renovatebot/config-help which recommended checking the dashboard: https://app.renovatebot.com/dashboard#github/Financial-Times/x-dash/189754427
https://docs.renovatebot.com/presets-default/#updatenotscheduled
> Bump existing branches outside work hours

- renovate.json
This is a PR to move the supportPolicy inside a node configuration object, as recommended [here](https://docs.renovatebot.com/node/).
All releases are currently raising PRs, so I think this could be a sensible first troubleshooting step.
> moved supportPolicy inside node config object

- renovate.json
When a dependency used by lots of repos is updated, Renovate creates many pull requests, which queue up a lot of builds on CircleCI, blocking other PRs across the entire organisation from building. This also happens when a Nori script applies a change to multiple repos. Before, our solution for this was to have Renovate open PRs out-of-hours, but that caused the queue to clog up for people working on different timezones or on a different work schedule. It also caused the Renovate PR notifications to be more easily missed.
As a solution, we will make Renovate open PRs in-hours again. It would be best if teams in Customer Products modified their CircleCI configuration so that all PRs opened by Renovate and Nori would wait-for-approval to start building so that they experience shorter …
> CPP-422 Allow renovate to open PRs in hours again

- README.md
- package-lock.json
- package.json
- renovate-config.json5
- renovate.json
- scripts/json5-to-json.js
- scripts/verify.sh
Renovate supports JSON5 but [not for shareable configs](https://github.com/renovatebot/renovate/issues/7674)
This PR adds a pre-commit githook to: 
- verify that the renovate.json file was not updated to avoid devs updating the incorrect file
- transpile the renovate config JSON5 to JSON.
- add the transpiled renovate.json file to be committed
> json5-to-json script and hook

- package.json
- scripts/test.sh
currently we have no tests to check that `renovate.json` has been compiled by the most recent `renovate-config.json`, we need to test that this happened on the pre-commit step, and was committed to the repo.
> add check to ensure file consistency

- README.md
- renovate-config.json5
- renovate.json
Add the commits for the changes that were in Financial-Times/renovate-config-next-beta#1.
> CPP-1375: add changes from renovate-config-next-beta
